### ISSUE TITLE
API-Änderung 

### ISSUE THREAD

**Issue by christianTF** [christianTF/LoxBerry-Plugin-aWATTar#1]
Benutzersymbol: peter.netbal
Peter Netbal sagt:
Wir haben folgende Änderung für das LOXONE API und das allgemeine aWATTar API Service für Österreich durchgeführt
Wir empfehlen ab sofort den Endpoint api.awattar.at statt api.awattar.com zu nutzen
Es wird ab sofort kein Zugangstoken mehr benötigt, das API kann also von jedem frei genutzt werden
Natürlich funktionieren bereits konfigurierte Aufrufe auf api.awattar.com mit Token weiterhin. 
Peter Netbal, aWATTar

https://www.loxwiki.eu/display/LOX/Anbinden+der+aWATTar+hourly+API

**Comment by eireit** [comment]
Hi
Is it possible for you to add norpool or entsoe prices?
