### ISSUE TITLE
Update Plugin to Loxberry V3.0

### ISSUE THREAD

**Issue by ChrisIDS6** [christianTF/LoxBerry-Plugin-aWATTar#7]
Hallo, 

ich wollte nachfragen, ob bereits ein Update dieses PlugIns für Loxberry V.3.0 geplant ist?

LG
Christoph

**Comment by christianTF** [comment]
Danke für den Hinweis!
Ist jetzt als V0.1.5 für LB30 verfügbar!

lg, Christian

**Comment by ChrisIDS6** [comment]
Danke für die rasche Umsetzung
