### ISSUE TITLE
Could not connect to MQTT Broker

### ISSUE THREAD

**Issue by ChrisIDS6** [christianTF/LoxBerry-Plugin-aWATTar#8]
Hallo, 

ich bekomme die Fehlermeldung "Could not connect to MQTT Broker" in den Logfiles vom plugin awattar. 

Im Plugin steht auch das das MQTT Gateway nicht installiert ist (Loxberry Version 3.0)

![grafik](https://user-images.githubusercontent.com/122130820/211171862-250f6e7c-166c-4694-8a2b-4258bd624c64.png)

MQTT Gateway ist konfiguiert - und läuft auch (Weather4loxone) läuft. 

Was kann das sein?

Danke jetzt schon für deine Hilfe

LG

**Comment by christianTF** [comment]
Oje, hier die Korrektur V0.1.6 für LoxBerry 3.0
https://github.com/christianTF/LoxBerry-Plugin-aWATTar/releases/tag/0.1.6

**Comment by ChrisIDS6** [comment]
Super, hat geklappt, Dankeschön.

Frage am Rande, wenn sich die Strompreise wiedermal normalisieren, ist es auch denkbar, das die übermittelten Werte negativ werden (siehe Strompreise 2018). Wenn ich nun den Awattar Aufschlag 3% hinzurechnen würde (p * 1,03) wäre das aber der falsche Betrag, da es bei negativen Werten sicherlich mal 0,97 zu rechnen wäre oder? Ich hab das nun in der Loxone gelöst, durch Wertvergleiche. In der Loxberry ist das noch nicht möglich oder?

**Comment by christianTF** [comment]
Ich weiß nicht genau, wie Awattar das macht. Es gab jetzt über Weihnachten auch wieder negative Preise, aber wie Awattar das intern rechnet, weiß ich auch nicht.

**Comment by christianTF** [comment]
Mir ist gerade eingefallen, wie Awattar das vermutlich löst:

Auf der Monatsrechnung steht ja der gewichtete Durchschnittspreis dieses Monats. Erst dort werden sie den Aufschlag rechnen.
Die Situation, dass jemand einen negativen Durchschnitts-Monatspreis hat, werden sie wohl noch nicht gehabt haben.
