### ISSUE TITLE
Advisor Werte kommen nicht an

### ISSUE THREAD

**Issue by ChrisIDS6** [christianTF/LoxBerry-Plugin-aWATTar#9]
Hallo, 
Ich bin schon wieder lästig, aber bei mir werden die Werte des Advisors nicht in der Loxone angezeigt. Wenn ich den Miniserver und den Loxberry gleichzeitig Reboote, dann zeigt mir die Loxone im Liveview einmal die Werte an. Stoppe ich den Liveview und starte  in erneut sind alle Werte auf 0 gesetzt. 
Wo könnte hier der Fehler liegen?

**Comment by christianTF** [comment]
Relevant ist erstmal, ob aktuelle Werte in der MQTT Incoming Overview ankommen. Die Daten haben auch einen Timestamp der letzten Übertragung.
